# -*- coding: utf-8 -*-
"""Session-3 DS Practical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uzgu2CD8QxNtw8OheZT1k_T09WEYJg6y

Day 1:Introduction to python for data science

#1.Google colab setup

1.2 Print a simple statement
"""

print("hello,excited to start data science.")

"""#2.Python basics

2.1 Variable assignment
"""

customer_name="john doe"
customer_age=28
customer_balance=120.75
print("customer:",customer_name)
print("age:",customer_age)
print("balance:",customer_balance)

"""2.2 Arithmetic operations"""

product_price=200
discount=product_price* 0.10 # 10% discount
final_price=product_price-discount
print("final price after discount:",final_price)

"""#3.Numpy basics

3.1 Create numpy arrays
"""

import numpy as np
sales=np.array([150,200,250,300,400,350,500]) # sales for each day
print("sales data:",sales)

"""3.2 Statistical analysis"""

print("average sales:",np.mean(sales))
print("highest sale:",np.max(sales))
print("lowest sale:",np.min(sales))

"""#4.pandas basics

4.1 create a data frame
"""

import pandas as pd
data={
    "customer":["alice","bob","charlie"],
    "age":[25,30,35],
    "amount spent":[120,200,250]
}
df=pd.DataFrame(data) # changed 'datafram' to 'dataFrame'
print(df)

"""4.2 Load and view a CSV file"""

from google.colab import files
import pandas as pd # Import pandas to make 'pd' available in this cell
uploaded = files.upload() # Upload your CSV file
df = pd.read_csv("students_dataset.csv") # Replace with your file name
df.head()

"""#5.Data manipulation with pandas

5.1 Filter high-spending customers
"""

# Check the actual column names in your DataFrame
print(df.columns)

# Assuming the column is named 'Marks', correct the code:
high_spenders = df[df["Marks"] > 150]
print(high_spenders)

"""5.2 Sorting customers by spending"""

# Replace 'amount spent' with the actual column name from your DataFrame, likely 'Marks'
df_sorted = df.sort_values(by="Marks", ascending=False)  # Using 'Marks' column for sorting
print(df_sorted)

"""5.3 Add a new column"""

df["Loyalty Points"] = df["Marks"] // 10 # Replace 'Amount Spent' with 'Marks'
print(df)

"""#6.saving processed data"""

df.to_csv("cleaned_customer_data.csv", index=False)
files.download("cleaned_customer_data.csv") # Download the file