# -*- coding: utf-8 -*-
"""Week 5 task 2-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xmseumVNUL4YN50q0yB8vY4tmR19Yyr9

2️⃣ Data Transformation: Scaling & Encoding
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder

def transform_data(df):
    # Ensure correct data types
    df['Annual_Income'] = df['Annual_Income'].astype(float)
    df['Spending_Score'] = df['Spending_Score'].astype(float)
    df['Purchase_Frequency'] = df['Purchase_Frequency'].astype(float)

    # Normalize Annual_Income and Spending_Score using Min-Max Scaling
    min_max_scaler = MinMaxScaler()
    df[['Annual_Income', 'Spending_Score']] = min_max_scaler.fit_transform(df[['Annual_Income', 'Spending_Score']])

    # Standardize Purchase_Frequency using Z-score Normalization
    standard_scaler = StandardScaler()
    df[['Purchase_Frequency']] = standard_scaler.fit_transform(df[['Purchase_Frequency']])

    # Convert Gender into numerical values using One-Hot Encoding
    df = pd.get_dummies(df, columns=['Gender'], drop_first=True)

    # Label encode the Preferred_Category column
    label_encoder = LabelEncoder()
    df['Preferred_Category'] = label_encoder.fit_transform(df['Preferred_Category'])

    return df

# Example usage
data = {
    'Annual_Income': [50000, 60000, 75000, 48000],
    'Spending_Score': [40, 70, 90, 20],
    'Purchase_Frequency': [5, 10, 15, 2],
    'Gender': ['Male', 'Female', 'Female', 'Male'],
    'Preferred_Category': ['Electronics', 'Clothing', 'Groceries', 'Clothing']
}
df = pd.DataFrame(data)

transformed_df = transform_data(df)
print(transformed_df)