# -*- coding: utf-8 -*-
"""Week 5 task 2-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLUI86RJlbc4YHhmCj1WLzOJN7Q9ICPC

1️⃣ Handling Missing Values & Duplicates
"""

import pandas as pd

def clean_dataset(df):
    # Identify and count missing values
    missing_values = df.isnull().sum()
    print("Missing Values per Column:\n", missing_values)

    # Fill missing numerical values with mean/median
    for col in df.select_dtypes(include=['number']).columns:
        df[col].fillna(df[col].median(), inplace=True)

    # Fill missing categorical values with mode
    for col in df.select_dtypes(include=['object']).columns:
        df[col].fillna(df[col].mode()[0], inplace=True)

    # Drop duplicate rows
    df.drop_duplicates(inplace=True)

    return df

# Example usage
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', None],
    'Age': [25, None, 30, 25, 22],
    'Salary': [50000, 60000, None, 50000, 48000]
}
df = pd.DataFrame(data)

print("Original Dataset:\n", df)
df_cleaned = clean_dataset(df)
print("\nCleaned Dataset:\n", df_cleaned)