# -*- coding: utf-8 -*-
"""Week 3 task 1-03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Ygp6AlkMgKP-HAgU0_h-pZz10P6fYng

3.Numpy basics
"""

import numpy as np

# Store a week's heart rate readings in a NumPy array (e.g., 7 readings, one for each day)
heart_rate_readings = np.array([72, 75, 68, 70, 74, 78, 69])

# Calculate the average, highest, and lowest heart rate
average_heart_rate = np.mean(heart_rate_readings)
highest_heart_rate = np.max(heart_rate_readings)
lowest_heart_rate = np.min(heart_rate_readings)

# Print the results
print("Average Heart Rate:", average_heart_rate)
print("Highest Heart Rate:", highest_heart_rate)
print("Lowest Heart Rate:", lowest_heart_rate)