# -*- coding: utf-8 -*-
"""Week 3 task 1-04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VlT8wGOMYmRcbxMyxfeHSLawYUeuDY4y

4.Pandas basics
"""

import pandas as pd

# Creating the DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [45, 50, 38, 60, 55],
    "Cholesterol": [200, 220, 180, 250, 230]
}

df = pd.DataFrame(data)
# Display the DataFrame
print(df)