# -*- coding: utf-8 -*-
"""Week 3 task 1-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dtFJt_Oj5ZDf-8JM8VTB_e5K8cqglUiW

1.Variable assignment
"""

# Storing patient details
patient_name = "Muthu Kumar "
patient_age = 35
patient_weight_kg = 75
patient_height_m = 1.75

# Calculating BMI
patient_bmi = patient_weight_kg / (patient_height_m ** 2)

# Displaying patient details
print(f"Patient Name: {patient_name}")
print(f"Age: {patient_age} years")
print(f"BMI: {patient_bmi:.2f}")